version: '3'

services:
  main-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    image: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    networks:
      - queue-network
    depends_on:
      - rabbitqueue
      - main-service-db
        
  rabbitqueue:
    image: rabbitmq:3.13-management
    container_name: rabbitqueue
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - queue-network

  main-service-db:
    image: mysql:8.0.29
    container_name: main-service-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mainpass
      MYSQL_DATABASE: mainservicedb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  queue-network: