version: '3'

services:
  rabbitqueue:
    image: rabbitmq:3.13-management
    container_name: rabbitqueue
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: userpass
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - queue-network

  main-service-db:
    image: mysql:8.0.29
    container_name: main-service-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mainpass
      MYSQL_DATABASE: mainservicedb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
  
  main-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: main-service
    container_name: main-service-container
    environment:
      ISSUER: "OnlineShoppen.dk"
      AUDIENCE: "OnlineShoppen.dk"
      KEY: "SZBNheG6DYChL2oyIo6Q3dAiK4sREZGPX6orWfH2Mk="
      CONNECTION_STRING: "server=192.168.65.254;user=user;password=userpass;database=mainservicedb"
      RABBITMQ_HOST: "rabbitqueue"
      RABBITMQ_PRODUCT_QUEUE: "productQueue"
      
    ports:
      - "8080:8080"
    networks:
      - queue-network
    depends_on:
      main-service-db:
        condition: service_healthy

networks:
  queue-network:
